spring.application.name=posbe

spring.profiles.active=DEV

spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logger configuration
# Log file name (relative path to the current directory or an absolute path)
logging.file.name=C://Users//Taniya Majumder//logs//pos//app.log
# The logging level for the root logger (can be TRACE, DEBUG, INFO, WARN, ERROR)
logging.level.root=INFO
# Pattern for the log entries (optional)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
# Limit the size of each log file (optional)
logging.file.max-size=10MB
# Keep a certain number of archived log files (optional)
logging.file.max-history=30
# Specify whether to roll over logs when the application restarts (optional)
logging.file.total-size-cap=100MB

# JWT Secret Key
jwt.secret=MyPOSApplicationSecretLongKeyForJWTGenerationAndValidationCreatedAt20260621
# 1 day in milliseconds
jwt.expiration=86400000

# ------------------------------------------------
# Email Configuration
# ------------------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jayanta4u2006@gmail.com
spring.mail.password=jpyz vwky bxio vqyz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Sender Name
application.mail.sender-name=POS Management System